Feat custom forms
bitpodio/bitpodjs pull request #17
Opened 2020-08-25 15:51 UTC by rishi9684

2020-08-25 16:08 UTC, SukantGujar requested changes
Casing needs to be corrected in a lot of places. I have marked a few of them.

2020-08-25 16:08 UTC, SukantGujar commented on pages/apps/_app/event/_id/editSiteSetting.vue
> +    sitesetting: {
camelCase the prop names.

2020-08-25 16:08 UTC, SukantGujar commented on pages/apps/_app/event/_id/newBadgeForm.vue
> +    // eslint-disable-next-line vue/require-prop-types
Why is this disable flag added? Also, newbadge should be camelCase

2020-08-25 16:08 UTC, SukantGujar commented on pages/event/_id/index.vue
> +      editeventform: false,
Casing please

2020-08-26 06:52 UTC, rishi9684 commented on pages/apps/_app/event/_id/editSiteSetting.vue
> +    sitesetting: {
camelcase done

2020-08-26 06:53 UTC, rishi9684 commented on pages/event/_id/index.vue
> +      editeventform: false,
done

2020-08-26 06:53 UTC, rishi9684 commented on pages/apps/_app/event/_id/newBadgeForm.vue
> +    // eslint-disable-next-line vue/require-prop-types
removed flag

2020-08-26 06:55 UTC, bitpod-io approved these changes

2020-08-26 06:56 UTC, SukantGujar approved these changes

2020-08-26 06:57 UTC, merged