Feat forms ui
bitpodio/bitpodjs pull request #23
Opened 2020-09-03 10:21 UTC by rishi9684

#App dropdown added
#Admin app layout added
#navigation content added 
#grid templates added for invitee, seat maps, badge

2020-09-03 16:16 UTC, SukantGujar requested changes

2020-09-03 16:16 UTC, SukantGujar commented on config/templates/grids/invitetemplate-grid/body.vue
> +    imgurl() {
Call it cdnUrl only

2020-09-03 16:16 UTC, SukantGujar commented on config/templates/grids/invitetemplate-grid/body.vue
> +    imgurl() {
In a component you don't need to import Nuxt config. It's already available as $config.

2020-09-03 16:18 UTC, rishi9684 commented on config/templates/grids/invitetemplate-grid/body.vue
> +    imgurl() {
ok

2020-09-03 16:40 UTC, rishi9684 commented on config/templates/grids/invitetemplate-grid/body.vue
> +    imgurl() {
cdnUrl  Done
#if i remove  import Nuxt config getting error

2020-09-04 06:57 UTC, rishi9684 commented on config/templates/grids/invitetemplate-grid/body.vue
> +    imgurl() {
added publicRuntimeConfig in nuxt config as discuss

2020-09-04 07:01 UTC, bitpod-io approved these changes

2020-09-04 07:01 UTC, SukantGujar approved these changes

2020-09-04 07:11 UTC, rishi9684 commented on config/templates/grids/invitetemplate-grid/body.vue
> +                      src="https://res.cloudinary.com/mytestlogo/image/upload/v1571132783/invitee-image.png"
added in config

2020-09-04 07:13 UTC, merged