Feat ui fixes
bitpodio/bitpodjs pull request #29
Opened 2020-09-07 16:39 UTC by rishi9684

#Mobile Fixes
#Login Box with Mobile UI

2020-09-07 16:51 UTC, SukantGujar requested changes

2020-09-07 16:51 UTC, SukantGujar commented on utility/index.js
> +      debugger
Remove all debuggers

2020-09-07 16:54 UTC, rishi9684 commented on utility/index.js
> +      debugger
Removed

2020-09-08 04:59 UTC, SukantGujar requested changes

2020-09-08 04:59 UTC, SukantGujar commented on nuxt.config.js
> +    eventUrl: process.env.GETEVENTURL || 'event.test.bitpod.io',
GET_EVENT_URL

2020-09-09 05:49 UTC, rishi9684 commented on nuxt.config.js
> +    eventUrl: process.env.GETEVENTURL || 'event.test.bitpod.io',
changed

2020-09-09 06:24 UTC, SukantGujar approved these changes

2020-09-09 06:35 UTC, SukantGujar approved these changes

2020-09-09 06:36 UTC, merged