Yash/add export csv button 911
bitpodio/bitpodjs pull request #338
Opened 2020-12-31 10:00 UTC by yash-bitpod

adds the `Export to CSV` button

2020-12-31 10:53 UTC, SukantGujar requested changes

2020-12-31 10:53 UTC, SukantGujar commented on components/common/grid/index.vue
> +  }
This name must not be hardcoded. Make it a combination of the grid name and date of export

2020-12-31 10:59 UTC, yash-bitpod commented on components/common/grid/index.vue
> +  }
Sure!

2021-01-04 09:22 UTC, yash-bitpod reviewed
~~https://github.com/bitpodio/bitpodjs/pull/338/files#diff-0d36627b3f885ddb8c97d3e6da8c020c9859b061b80a7d315e56c19ec9dc4181R55-R56~~

~~WIP for stacking fix.~~

2021-01-05 08:31 UTC, SukantGujar approved these changes

2021-01-05 08:31 UTC, merged