match grid format for csv export
bitpodio/bitpodjs pull request #346
Opened 2021-01-06 11:11 UTC by yash-bitpod

2021-01-06 14:30 UTC, SukantGujar requested changes

2021-01-06 14:30 UTC, SukantGujar commented on config/apps/event/content/event.js
> +            console.debug(tags)
Why we need the `debug`.

2021-01-06 14:33 UTC, yash-bitpod commented on config/apps/event/content/event.js
> +            console.debug(tags)
My bad, missed removing it from the commit. I added it while testing to get logs in-case of something breaking. Will remove in the next commit!

2021-01-07 05:27 UTC, SukantGujar approved these changes

2021-01-07 05:28 UTC, merged