Feat image gallery upload
bitpodio/bitpodjs pull request #39
Opened 2020-09-17 17:17 UTC by Amartyakumar

Added the image upload functionality

2020-09-17 17:21 UTC, SukantGujar requested changes

2020-09-17 17:21 UTC, SukantGujar commented on pages/apps/_app/event/_id/index.vue
> +        .catch((e) => console.log('Error', e))
Don't mix promises with async

2020-09-18 06:47 UTC, SukantGujar approved these changes

2020-09-22 13:28 UTC, SukantGujar requested changes

2020-09-22 13:28 UTC, SukantGujar commented on components/common/copy/index.vue
> +            .then(() => {
No promise, use async await.

2020-09-22 13:28 UTC, SukantGujar commented on components/common/copy/index.vue
> +      writeBtn.addEventListener('click', () => {
Why is this listener required? This code will keep on adding listener on each onCopy method call. You need to remove the listener once the copy is over.

2020-09-22 13:28 UTC, SukantGujar commented on pages/apps/_app/event/_id/index.vue
> +          }, 5000)
Why a timeout of 5 seconds here?

2020-09-22 13:28 UTC, SukantGujar commented on pages/apps/_app/event/_id/index.vue
> +        if (res) {
There's no setTimeout used here. Why is it used earlier?

2020-09-22 17:20 UTC, Amartyakumar commented on pages/apps/_app/event/_id/index.vue
> +        if (res) {
resolved

2020-09-22 17:20 UTC, Amartyakumar commented on pages/apps/_app/event/_id/index.vue
> +          }, 5000)
resolved

2020-09-22 17:20 UTC, Amartyakumar commented on components/common/copy/index.vue
> +      writeBtn.addEventListener('click', () => {
resolved

2020-09-22 17:20 UTC, Amartyakumar commented on components/common/copy/index.vue
> +            .then(() => {
resolved

2020-09-23 05:02 UTC, SukantGujar approved these changes

2020-09-23 05:30 UTC, merged