Feb issue v8
bitpodio/bitpodjs pull request #456
Opened 2021-03-01 14:02 UTC by rishi9684

#issue resolved
#video console error removed

2021-03-01 14:18 UTC, SukantGujar requested changes

2021-03-01 14:18 UTC, SukantGujar commented on nuxt.config.js
> +      // {
Remove

2021-03-01 14:18 UTC, SukantGujar commented on pages/apps/_app/attendee/_id/index.vue
> +      if (liveStart && liveEnd) {
Just `return liveStart && liveEnd;`

2021-03-01 14:26 UTC, rishi9684 commented on pages/apps/_app/attendee/_id/index.vue
> +      if (liveStart && liveEnd) {
done

2021-03-01 14:29 UTC, SukantGujar requested changes

2021-03-01 14:29 UTC, SukantGujar commented on pages/apps/_app/attendee/_id/index.vue
> +      if (liveStart && liveEnd) {
No need for if, just return.

2021-03-02 05:17 UTC, SukantGujar approved these changes

2021-03-02 05:17 UTC, merged