Feat dynamic stepper:Added the stepper functionality and dynamically changing the Status
bitpodio/bitpodjs pull request #58
Opened 2020-09-28 14:10 UTC by Amartyakumar

2020-09-28 15:26 UTC, SukantGujar requested changes

2020-09-28 15:26 UTC, SukantGujar commented on pages/apps/_app/event/_id/index.vue
> +      console.log('status1', status)
Remove

2020-09-28 15:26 UTC, SukantGujar commented on pages/apps/_app/event/_id/index.vue
> +        console.log('Error', e)
Add more context. What operation was tried? What were the inputs?

2020-09-28 15:26 UTC, SukantGujar commented on pages/event/_id/index.vue
> +      // ready: false,
Remove

2020-09-28 15:26 UTC, SukantGujar commented on pages/event/_id/index.vue
> +        status === 'Not ready' ||
Simply return this expression. No need for if.

2020-09-28 15:26 UTC, SukantGujar commented on pages/event/_id/index.vue
> +      if (status === 'Sold out' || status === 'Registration closed') {
Same here and in the below if statement.

2020-09-28 16:47 UTC, Amartyakumar commented on pages/event/_id/index.vue
> +      // ready: false,
This file is not in use at the moment.This branch was created earlier

2020-09-28 16:48 UTC, Amartyakumar commented on pages/event/_id/index.vue
> +        status === 'Not ready' ||
This file is not in use now

2020-09-28 16:48 UTC, Amartyakumar commented on pages/event/_id/index.vue
> +      if (status === 'Sold out' || status === 'Registration closed') {
This file is not in use

2020-09-30 04:36 UTC, SukantGujar requested changes

2020-09-30 04:36 UTC, SukantGujar commented on pages/event/_id/index.vue
> +      if (status === 'Sold out' || status === 'Registration closed') {
Then delete this file please.

2020-10-01 09:38 UTC, SukantGujar approved these changes

2020-10-01 09:38 UTC, merged