May issue 432
bitpodio/bitpodjs pull request #696
Opened 2021-05-25 14:45 UTC by rishi9684

#432 Resolved
#635 Resolved
#685 Resolved

2021-05-25 14:47 UTC, SukantGujar requested changes

2021-05-25 14:47 UTC, SukantGujar commented on components/common/theme/index.vue
> +    const theme = localStorage.getItem('darkTheme')
Prepend the userid to the key name.

2021-05-26 06:34 UTC, rishi9684 commented on components/common/theme/index.vue
> +    const theme = localStorage.getItem('darkTheme')
added prefix as hashid

2021-05-26 06:37 UTC, SukantGujar approved these changes

2021-05-26 06:43 UTC, merged