feat_grid_activity:REST type changes and filterEnable
bitpodio/bitpodjs pull request #9
Opened 2020-08-19 11:16 UTC by kapilchothe1

Added REST type changes like pagination,sorting,filtering, searching and also added changes for filterEnablefields. 
Added Activity navigation menu and its functionality.

2020-08-19 11:28 UTC, SukantGujar requested changes

2020-08-19 11:28 UTC, SukantGujar commented on config/apps/event/rest/index.js
> +    const skip = (page - 1) * (itemsPerPage || 10)
Don't need || 10 here

2020-08-19 11:28 UTC, SukantGujar commented on config/apps/event/rest/index.js
> +      `https://event.test.bitpod.io/svc/api/${modelName}s?filter=${JSON.stringify(
The url hostname should come from env variables or from the Nuxt router url.

2020-08-19 13:13 UTC, kapilchothe1 commented on config/apps/event/rest/index.js
> +    const skip = (page - 1) * (itemsPerPage || 10)
When removed '|| 10' from line 9 , page is getting hang for sometime when page loads first time due to large data.

2020-08-19 13:18 UTC, kapilchothe1 commented on config/apps/event/rest/index.js
> +      `https://event.test.bitpod.io/svc/api/${modelName}s?filter=${JSON.stringify(
Resolved

2020-09-24 03:59 UTC, SukantGujar approved these changes

2020-09-24 04:00 UTC, merged