Bug domain favicon
bitpodio/bitpodjs pull request #994
Opened 2021-07-21 14:10 UTC by rishi9684

#favicon icon added as per domain
#title added as domain

2021-07-21 14:19 UTC, SukantGujar requested changes

2021-07-21 14:19 UTC, SukantGujar commented on layouts/admin.vue
> +      if (process.client) {
Test if this works locally, when the hostname would just be localhost.

2021-07-21 14:19 UTC, SukantGujar commented on layouts/default.vue
> +    getDomain() {
This code is being repeated several times, create a mixin.

2021-07-22 06:42 UTC, rishi9684 commented on layouts/admin.vue
> +      if (process.client) {
Yes its working fine for localhost, its display title as localhost

2021-07-22 06:43 UTC, rishi9684 commented on layouts/default.vue
> +    getDomain() {
created mixin for getDomain()

2021-07-22 06:52 UTC, SukantGujar approved these changes

2021-07-22 06:55 UTC, rishi9684 commented on layouts/admin.vue
> +      if (process.client) {
![image](https://user-images.githubusercontent.com/68382096/126600260-7c9fc4dc-892e-446d-8897-6100b264af3c.png)

2021-07-22 07:04 UTC, merged